// checksum 0x9a77 version 0x30001
/*
  This file was generated by the Mobile Qt Application wizard of Qt Creator.
  MainWindow is a convenience class containing mobile device specific code
  such as screen orientation handling.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QtGui/QMainWindow>
#include "QLabel"
#include <xmmsclient/xmmsclient.h>

namespace Ui {
    class MainWindow;
}

class MainWindow : public QMainWindow
{

    Q_OBJECT
public:
    enum ScreenOrientation {
        ScreenOrientationLockPortrait,
        ScreenOrientationLockLandscape,
        ScreenOrientationAuto
    };
    explicit MainWindow(QWidget *parent = 0);
    virtual ~MainWindow();
    void setOrientation(ScreenOrientation orientation);
    void showExpanded();
    void get_song_info();
    void setLabelText(QString label);


public slots:

private slots:
    void on_play_bt_clicked();

    void on_stop_bt_clicked();

    void on_next_bt_clicked();

    void on_prev_bt_clicked();




private:

    Ui::MainWindow *ui;

signals:


};

#endif // MAINWINDOW_H
