// checksum 0x9a77 version 0x30001
/*
  This file was generated by the Mobile Qt Application wizard of Qt Creator.
  MainWindow is a convenience class containing mobile device specific code
  such as screen orientation handling.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QtGui/QMainWindow>
#include "QLabel"
#include <xmmsclient/xmmsclient.h>

namespace Ui {
    class MainWindow;
}

class MainWindow : public QMainWindow
{

    Q_OBJECT
public:
    enum ScreenOrientation {
        ScreenOrientationLockPortrait,
        ScreenOrientationLockLandscape,
        ScreenOrientationAuto
    };
    explicit MainWindow(QWidget *parent = 0);
    virtual ~MainWindow();
    void setOrientation(ScreenOrientation orientation);
    void showExpanded();



public slots:
    void setLabelText(QString label);


    void get_song_info();
private slots:
    void on_play_bt_clicked();

    void on_stop_bt_clicked();

    void on_next_bt_clicked();

    void on_prev_bt_clicked();

    //int on_playback_status_changed( xmmsv_t *value, void *user_data )();

    //static void xmms_callbacks();

    void connect_xmms();

    //void setLabelText();





private:
    Ui::MainWindow *ui;

    //void setLabelText();
      int my_current_id (xmmsv_t *value, void *userdata);

      int on_playback_status_changed( xmmsv_t *value, void *user_data );

      void xmms_callbacks();

     void xmmsc_result_notifier_set_and_unref (xmmsc_result_t *result, xmmsc_result_notifier_t func, void *user_data);

signals:

   //void get_song_info();



};

#endif // MAINWINDOW_H
